In [26]:
print("Hello, World!")

Hello, World!


In [27]:
x = 5
print(x)
print(type(x))

5
<class 'int'>


In [28]:
print('x = ' + str(x))

x = 5


In [29]:
x = 0.5
y = 3
print(y**2 + 2*x)

10.0


In [30]:
print(y / x)

6.0


In [31]:
z = 5
print(y / z)

0.6


In [32]:
print(y / float(z))

0.6


In [33]:
print(int(x))

0


In [34]:
winter = True
rain = False

snow = winter and rain
print(snow)

False


In [35]:
summer = not winter
print(summer)

False


In [36]:
bad_weather = winter or rain
print(bad_weather)

True


In [37]:
print(3 == 5)

False


In [38]:
print(3 < 4)
print(4 < 4)

True
False


In [39]:
print(4 <= 4)

True


In [40]:
print(2+2 == 5)

False


In [41]:
print(5 % 3)

2


In [42]:
def square_plus(x, y):
    print("square of x = " + str(x) + " added by " + str(y))
    return x**2 + y

print(square_plus(3, 1))

square of x = 3 added by 1
10


In [43]:
def set_to(x, value):
    print("set x to " + str(value))
    x = value
    
y = 5
set_to(y, square_plus(3, 1))
print(y)

square of x = 3 added by 1
set x to 10
5


In [44]:
def abs(x):
    if x < 0:
        return -x
    
    return x

print(abs(3), abs(-3))

3 3


In [45]:
i = 4

while i >= 0:
    print(i)
    i -= 1

4
3
2
1
0


In [46]:
for i in range(5):
    print(i)

0
1
2
3
4


In [47]:
for c in "WOW!":
    print(c)

W
O
W
!


In [48]:
def factorial(n):
    if n == 0:
        return 1
    else:
        return n * factorial(n-1)
    
print(factorial(42))

1405006117752879898543142606244511569936384000000000


In [49]:
import math

print(math.exp(1))
print(math.sin(0))

2.718281828459045
0.0


In [50]:
from math import sin, cos
print(sin(3)**2 + cos(3)**2)

0.9999999999999999


In [51]:
xs = [1, 2, 3, 4]
print(xs[0])

1


In [52]:
print(len(xs))
print(sum(xs))

4
10


In [53]:
print(xs)

[1, 2, 3, 4]


In [54]:
print([1, 2]*2 + [3])

[1, 2, 1, 2, 3]


In [55]:
some_objects = []
some_objects.append("a")
some_objects.append(True)
some_objects.append(3)
print(some_objects)

['a', True, 3]


In [56]:
print(type(some_objects))

<class 'list'>


In [57]:
del some_objects[0]
print(some_objects)

[True, 3]


In [58]:
some_objects.remove(3)
print(some_objects)

[True]


In [59]:
nums = range(20)
print(nums)
print(nums[:10])
print(nums[1:10])
print(nums[::2])
print(nums[::-1])

range(0, 20)
range(0, 10)
range(1, 10)
range(0, 20, 2)
range(19, -1, -1)


In [60]:
squares = [x**2 for x in range(10)]
print(squares)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [61]:
squaring = lambda x: x**2
print(squaring(3))

9


In [62]:
whos

Variable       Type                          Data/Info
------------------------------------------------------
a              complex128                    4j
abs            function                      <function abs at 0x000002420993ED30>
b              ndarray                       2x4x6x8: 384 elems, type `float64`, 3072 bytes
bad_weather    bool                          True
c              str                           !
cos            builtin_function_or_method    <built-in function cos>
factorial      function                      <function factorial at 0x000002420993EF70>
i              int                           4
math           module                        <module 'math' (built-in)>
np             module                        <module 'numpy' from 'D:\<...>ges\\numpy\\__init__.py'>
nums           range                         range(0, 20)
rain           bool                          False
set_to         function                      <function set_to at 0x000002420993E790>


In [63]:
import numpy as np

print(np.sqrt(-1 + 0j))

1j


In [64]:
b = np.array([2, 4, 6, 8])
print(b)

[2 4 6 8]


In [65]:
print(b.shape)

(4,)


In [66]:
b2 = b.reshape((4, 1))
print(b2.shape)

(4, 1)


In [67]:
print(b.dot(b2))

[120]


In [68]:
b3 = np.linspace(1, 3, 5)
print(b3)

[1.  1.5 2.  2.5 3. ]


In [69]:
b4 = np.arange(0, 11, 2)
print(b4)

[ 0  2  4  6  8 10]


In [70]:
A = np.array(np.mat('1 2 3; 4 5 6; 7 8 0'))
print(A)
print(A.shape)

[[1 2 3]
 [4 5 6]
 [7 8 0]]
(3, 3)


In [71]:
print(A.T)

[[1 4 7]
 [2 5 8]
 [3 6 0]]


In [72]:
print(A[0])

[1 2 3]


In [73]:
print(A[1, 2])

6


In [74]:
print(A[:, 2])

[3 6 0]


In [75]:
print(A[0, [0, 1, 0]])

[1 2 1]


In [76]:
A[2, 2] = 9
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [77]:
print(A.dtype)

int32


In [78]:
print(A.astype(float))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [79]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [80]:
print(np.ones((2, 2, 2)))

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


In [81]:
np.random.seed(1)
A + np.random.rand(3, 3)

array([[1.417022  , 2.72032449, 3.00011437],
       [4.30233257, 5.14675589, 6.09233859],
       [7.18626021, 8.34556073, 9.39676747]])

In [82]:
A = np.array(np.mat('[1 2 3; 4 5 6; 7 8 10]'))

In [83]:
A2 = A.T
A2

array([[ 1,  4,  7],
       [ 2,  5,  8],
       [ 3,  6, 10]])

In [84]:
A3 = A ^ A
A3

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [85]:
A[1]

array([4, 5, 6])

In [86]:
A[0, 2]

3

In [87]:
A[2,:3]

array([ 7,  8, 10])

In [88]:
A[:,2]

array([ 3,  6, 10])

In [89]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [90]:
np.full((2,4), 5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

In [91]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [92]:
import numpy as np

In [93]:
np.random.rand(3,4)

array([[0.53881673, 0.41919451, 0.6852195 , 0.20445225],
       [0.87811744, 0.02738759, 0.67046751, 0.4173048 ],
       [0.55868983, 0.14038694, 0.19810149, 0.80074457]])

In [94]:
np.random.randn(3,4)

array([[ 0.7299756 ,  0.37299379,  0.53381091, -0.0919733 ],
       [ 1.91382039,  0.33079713,  1.14194252, -1.12959516],
       [-0.85005238,  0.96082   , -0.21741818,  0.15851488]])

In [111]:
x = np.ndarray([1, 0, 2])
x

array([], shape=(1, 0, 2), dtype=float64)

In [110]:
y = x -1
print(y)

[]


In [97]:
x.T.dot(y)

ValueError: shapes (2,0,1) and (1,0,2) not aligned: 1 (dim 2) != 0 (dim 1)

In [98]:
def abs(x):
    if x < 0:
        return -x
    return x
print(abs(3), abs(-5))

3 5


In [99]:
for i in range(5):
    print(i)
for c in "WOW!":
    print(c)

0
1
2
3
4
W
O
W
!


In [100]:
def what_am_i(n):
    i= 0
    while i< n:
        s = ""
        for j in range(n):
            if j == i or j == n-i-1:
                s += "*"
            else:
                s += ""
        print(s)
        i+= 1
what_am_i(5)

**
**
*
**
**


In [101]:
xs= [1, 2, 3, 4]
print(xs[0])
print(xs)
print(len(xs), sum(xs))
print([1, 2] + [3]*2 + [])
print("ab"* 3)

1
[1, 2, 3, 4]
4 10
[1, 2, 3, 3]
ababab


In [102]:
some_objects= []
some_objects.append("a")
some_objects.append(True)
some_objects.append(3)
print(some_objects[0])
print(some_objects)
del some_objects[0]
print(some_objects)
some_objects.remove(3)
print(some_objects)

a
['a', True, 3]
[True, 3]
[True]


In [103]:
nums = range(20)
print(nums[1:10])
print(nums[:10])
print(nums[5:])
print(nums[:])
print(nums[10::-1])
print(nums[:10:-1])
print(nums[3:15:4])

range(1, 10)
range(0, 10)
range(5, 20)
range(0, 20)
range(10, -1, -1)
range(19, 10, -1)
range(3, 15, 4)


In [104]:
import numpy as np

In [108]:
a = np.sqrt(-16 + 0j)
print(a)

4j


In [117]:
x = np.array([1, 0, 2])
x

array([1, 0, 2])

In [118]:
b = np.array([2, 4, 6, 8])
print(b)

[2 4 6 8]


In [119]:
b2 = b.reshape(4, 1)
b2

array([[2],
       [4],
       [6],
       [8]])

In [120]:
print(b.dot(b2))

[120]


In [123]:
A = np.array(np.mat('[1 2 3; 4 5 6; 7 8 0]'))
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 0]]


In [124]:
A2 = A.T
A2

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 0]])

In [125]:
A.shape

(3, 3)

In [126]:
A.dtype

dtype('int32')

In [137]:
x = np.array([-1, 0, 2])
x

array([-1,  0,  2])

In [138]:
y = x -1
y

array([-2, -1,  1])

In [143]:
y1 = y.T

In [144]:
y = y * y1
y

array([4, 1, 1])

In [130]:
x = x.T.dot(y)
x

4

In [142]:
np.pi * x

array([-3.14159265,  0.        ,  6.28318531])

In [135]:
np.dot(x,y.T)

array([-8, -4,  4])